-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "16")

-- Settings
hl.config({
    decoration = {
        blur = {
            contrast = 1.07,
            enabled = true,
            noise = 0.022,
            popups = true,
            size = 6,
            vibrancy = 0.3,
            xray = true,
        },
        rounding = 8,
    },
    ecosystem = {
        no_donation_nag = false,
    },
    general = {
        gaps_out = 7,
    },
    misc = {
        disable_splash_rendering = true,
    },
})

-- Monitors
hl.monitor({
    output = "HDMI-A-2",
    disabled = false,
    mode = "1920x1080@74.97Hz",
    position = "663x-352",
    scale = 0.83,
    cm = "srgb",
})
