-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1080@60.01", position = "2656x-64", scale = 1.00 })
hl.monitor({ output = "HDMI-A-2", mode = "1920x1080@75.00", position = "736x-64", scale = 1.00 })
